r[mail function]
SMTP = smtp.gmail.com
smtp_port = 587
sendmail_from = ambatuka69@gmail.com
sendmail_path = "\"C:\xampp\sendmail\sendmail.exe\" -t"

[PHP]
error_reporting = E_ALL
display_errors = On
log_errors = On
error_log = "php_error.log"
